POST http://localhost:3100/api/v1/users
Content-Type: application/json

{
  "name": "john k",
  "email": "john@me.com",
  "password": "1234",
  "contact": "38399238"
}

###
GET http://localhost:3100/api/v1/users
Accept: application/json

###
POST http://localhost:3100/api/v1/tasks
Content-Type: application/json

{
  "title": "some title"
}

###
GET http://localhost:3100/api/v1/tasks
Accept: application/json

###

GET http://localhost:3000/api/v1/tasks/fb8316bb-3e33-4749-88ab-4d68d02976c0
Accept: application/json

###


###
GET http://localhost:3000/api/v1/health
Accept: application/json

###

